### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by Wolf-Fivousix** [Wolf-Fivousix/Racket#2]
Check out all the **sweet** functionality that is now live!
Splash page is a work in progress.

**Comment by evhumphrey** [comment]
Looks good! 🎉 

Here's some feedback:

- [ ] Make sure to style your logout button; I suggest putting it at the bottom of the ServersIndex or ChannelIndex
- [ ] I'd remove the `Forgot your password?` for now; you can add it later if you decide to implement a password reset feature
- [ ] Update your logo 
- [ ] Add a little more spacing between the `password` and `continue` in your `/signup`
- [ ] Add `cursor: pointer` to your splash page buttons
- [ ] I'd add a little more space between the top of your page and the login button

**Comment by Wolf-Fivousix** [comment]
Issues corrected.
Also changed "Forgot your password?" to a "Back to Home Page" link.
Splash buttons also linking to GitHub and Email.
